# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab6.proto',
  package='restcompare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nlab6.proto\x12\x0brestcompare\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\x90\x02\n\x0bRestCompare\x12\x33\n\x03\x61\x64\x64\x12\x13.restcompare.addMsg\x1a\x15.restcompare.addReply\"\x00\x12?\n\x08rawImage\x12\x18.restcompare.rawImageMsg\x1a\x17.restcompare.imageReply\"\x00\x12H\n\ndotproduct\x12\x1a.restcompare.dotProductMsg\x1a\x1c.restcompare.dotProductReply\"\x00\x12\x41\n\tjsonImage\x12\x19.restcompare.jsonImageMsg\x1a\x17.restcompare.imageReply\"\x00\x62\x06proto3'
)




_ADDMSG = _descriptor.Descriptor(
  name='addMsg',
  full_name='restcompare.addMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='restcompare.addMsg.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='restcompare.addMsg.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=57,
)


_RAWIMAGEMSG = _descriptor.Descriptor(
  name='rawImageMsg',
  full_name='restcompare.rawImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='restcompare.rawImageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=85,
)


_DOTPRODUCTMSG = _descriptor.Descriptor(
  name='dotProductMsg',
  full_name='restcompare.dotProductMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='restcompare.dotProductMsg.a', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='restcompare.dotProductMsg.b', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=124,
)


_JSONIMAGEMSG = _descriptor.Descriptor(
  name='jsonImageMsg',
  full_name='restcompare.jsonImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='restcompare.jsonImageMsg.img', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=153,
)


_ADDREPLY = _descriptor.Descriptor(
  name='addReply',
  full_name='restcompare.addReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='restcompare.addReply.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=178,
)


_DOTPRODUCTREPLY = _descriptor.Descriptor(
  name='dotProductReply',
  full_name='restcompare.dotProductReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dotproduct', full_name='restcompare.dotProductReply.dotproduct', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=217,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='imageReply',
  full_name='restcompare.imageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='restcompare.imageReply.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='restcompare.imageReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=262,
)

DESCRIPTOR.message_types_by_name['addMsg'] = _ADDMSG
DESCRIPTOR.message_types_by_name['rawImageMsg'] = _RAWIMAGEMSG
DESCRIPTOR.message_types_by_name['dotProductMsg'] = _DOTPRODUCTMSG
DESCRIPTOR.message_types_by_name['jsonImageMsg'] = _JSONIMAGEMSG
DESCRIPTOR.message_types_by_name['addReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['dotProductReply'] = _DOTPRODUCTREPLY
DESCRIPTOR.message_types_by_name['imageReply'] = _IMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addMsg = _reflection.GeneratedProtocolMessageType('addMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.addMsg)
  })
_sym_db.RegisterMessage(addMsg)

rawImageMsg = _reflection.GeneratedProtocolMessageType('rawImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _RAWIMAGEMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.rawImageMsg)
  })
_sym_db.RegisterMessage(rawImageMsg)

dotProductMsg = _reflection.GeneratedProtocolMessageType('dotProductMsg', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.dotProductMsg)
  })
_sym_db.RegisterMessage(dotProductMsg)

jsonImageMsg = _reflection.GeneratedProtocolMessageType('jsonImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _JSONIMAGEMSG,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.jsonImageMsg)
  })
_sym_db.RegisterMessage(jsonImageMsg)

addReply = _reflection.GeneratedProtocolMessageType('addReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.addReply)
  })
_sym_db.RegisterMessage(addReply)

dotProductReply = _reflection.GeneratedProtocolMessageType('dotProductReply', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.dotProductReply)
  })
_sym_db.RegisterMessage(dotProductReply)

imageReply = _reflection.GeneratedProtocolMessageType('imageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:restcompare.imageReply)
  })
_sym_db.RegisterMessage(imageReply)



_RESTCOMPARE = _descriptor.ServiceDescriptor(
  name='RestCompare',
  full_name='restcompare.RestCompare',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=265,
  serialized_end=537,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='restcompare.RestCompare.add',
    index=0,
    containing_service=None,
    input_type=_ADDMSG,
    output_type=_ADDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='rawImage',
    full_name='restcompare.RestCompare.rawImage',
    index=1,
    containing_service=None,
    input_type=_RAWIMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='dotproduct',
    full_name='restcompare.RestCompare.dotproduct',
    index=2,
    containing_service=None,
    input_type=_DOTPRODUCTMSG,
    output_type=_DOTPRODUCTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='jsonImage',
    full_name='restcompare.RestCompare.jsonImage',
    index=3,
    containing_service=None,
    input_type=_JSONIMAGEMSG,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTCOMPARE)

DESCRIPTOR.services_by_name['RestCompare'] = _RESTCOMPARE

# @@protoc_insertion_point(module_scope)
